title: Game Curious Montreal - Curieux de Jeux Montr√©al
url: https://gamecuriousmtl.mrgs.ca
author: Game Curious Montreal Collective
timezone: America/Toronto

permalink: pretty
markdown: kramdown

email: gamecuriousmtl@gmail.com
anonemail: ssahmrgs@gmail.com
fb: https://facebook.com/gamecuriousmtl
twitter: https://twitter.com/game_curious
itch: https://gamecuriousmtl.itch.io

# partner links
qpirg: https://qpirgconcordia.org
aveq: https://aveq-nous.ca
pixelles: https://pixelles.ca
ataqe: https://facebook.com/ataquepodcast
mrgs: http://mrgs.ca

plugins:
        - jekyll-sitemap

collections:
        policing:
            output: true
        feminism:
            output: true
        decolonize:
            output: true
        immigration:
            output: true
